apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-shoppingcartservice
  labels:
    app: docker-k8s-shoppingcartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-shoppingcartservice
  template:
    metadata:
      labels:
        app: docker-k8s-shoppingcartservice
    spec:
      containers:
        - name: docker-k8s-shoppingcartservice
          image: it19145280/shoppingcartservice
          ports:
          - containerPort: 8080